# Generated by Django 2.1.3 on 2019-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='about',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
